# Generated by Django 2.1.5 on 2019-02-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_passFlag',
            field=models.BooleanField(default=True),
        ),
    ]
