# Generated by Django 2.1.5 on 2019-02-12 05:10
"""
Generated by Django 2.1.5 on 2019-02-12 05:10
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Generated by Django 2.1.5 on 2019-02-12 05:10
    """

    dependencies = [
        ('Surveyapp', '0002_employee_emp_passflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_passFlag',
        ),
    ]
