# Generated by Django 2.1.5 on 2019-02-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyapp', '0003_remove_employee_emp_passflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='SaveStatus',
            field=models.BooleanField(default=False),
        ),
    ]
