# Generated by Django 2.1.7 on 2019-02-15 06:21
"""
Generated by Django 2.1.5 on 2019-02-13 05:31
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Generated by Django 2.1.5 on 2019-02-13 05:31
    """

    dependencies = [
        ('Surveyapp', '0004_surveyresponse_savestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyemployee',
            name='employee',
        ),
        migrations.AddField(
            model_name='surveyemployee',
            name='employee',
            field=models.ManyToManyField(to='Surveyapp.Employee'),
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question',
            field=models.ManyToManyField(to='Surveyapp.Question'),
        ),
    ]
